// This file is normally generated by FlutterFire CLI.
// If you add or remove platforms, re-run `flutterfire configure`.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are configured only for Android in this project.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRG8HhY9K1i0JqgSgM5WnE61oK1nC4TVw',
    appId: '1:486141115032:android:56b7b6db35fdde173c2eed',
    messagingSenderId: '486141115032',
    projectId: 'suhub-prod',
    storageBucket: 'suhub-prod.firebasestorage.app',
  );
}
